---
services:
  db:
    image: postgres:18
    container_name: insta_bio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: insta_bio_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:

